In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv("/content/drive/MyDrive/00 IITR INTERNSHIP/00_final_dataset.csv")

In [12]:
import pandas as pd
df = pd.get_dummies(df, columns=['family'], prefix='family', drop_first=True)
print("DataFrame shape after one-hot encoding 'family' column:")
print(df.shape)
print("First 5 rows of DataFrame after encoding:")
display(df.head())

DataFrame shape after one-hot encoding 'family' column:
(5007, 22)
First 5 rows of DataFrame after encoding:

,file_name,apk_size,permission_count,api_count,opcode_count,intent_count,PERM,API,INTENT,OPCODE,...,family_Riskware,family_SMS,family_android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_DELETED android.appwidget.action.APPWIDGET_ENABLED android.appwidget.action.APPWIDGET_DISABLED com.android.vending.INSTALL_REFERRER com.google.android.c2dm.intent.RECEIVE com.google.android.gms.measurement.UPLOAD,family_android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_UPDATE com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION,family_android.intent.action.BOOT_COMPLETED android.net.conn.CONNECTIVITY_CHANGE com.urbanairship.push.CHANNEL_UPDATED com.urbanairship.push.OPENED com.urbanairship.push.RECEIVED com.urbanairship.push.DISMISSED com.android.vending.INSTALL_REFERRER android.appwidget.action.APPWIDGET_UPDATE com.android.vending.INSTALL_REFERRER android.intent.action.PACKAGE_REPLACED com.urbanairship.push.OPENED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.amazon.device.messaging.intent.REGISTRATION com.amazon.device.messaging.intent.RECEIVE,family_android.provider.Telephony.SMS_RECEIVED,family_com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.RECEIVE net.peakgames.Yuzbir.AUTO_CAMPAIGN_ACTION net.peakgames.Yuzbir.TIME_BONUS_ACTION,family_com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.jamplay.jamplaymobile.android.intent.APPBOY_PUSH_RECEIVED com.jamplay.jamplaymobile.android.intent.APPBOY_NOTIFICATION_OPENED com.android.vending.INSTALL_REFERRER,family_com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION,family_com.inmobi.share.id android.net.conn.CONNECTIVITY_CHANGE com.android.vending.billing.IN_APP_NOTIFY com.android.vending.billing.RESPONSE_CODE com.android.vending.billing.PURCHASE_STATE_CHANGED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION android.net.conn.CONNECTIVITY_CHANGE com.google.android.gms.measurement.UPLOAD android.provider.Telephony.SECRET_CODE
0,51ac87b5dc1c12f3dfe43cd2114c28a845699308a2803c...,246751,23.0,889.0,27530.0,8.0,INTERNET ACCESS_NETWORK_STATE CALL_PHONE SEND_...,forceLoad setInternalPageChangeListener execut...,android.provider.Telephony.SMS_RECEIVED androi...,invoke-direct return-void add-double unresolve...,...,False,False,False,False,False,False,False,False,False,False
1,1b16adaa855a73b75224d76058b72e6b39d8178a58ad08...,251248,16.0,1305.0,36584.0,7.0,SEND_SMS READ_CONTACTS READ_EXTERNAL_STORAGE W...,setInternalPageChangeListener setPassword getM...,android.intent.action.BOOT_COMPLETED android.i...,invoke-direct new-instance invoke-direct iput-...,...,False,False,False,False,False,False,False,False,False,False
2,3ef61e6781e76c13ab7d5519bc094db1dd2bfbf1ea8bf1...,230784,23.0,887.0,27394.0,8.0,INTERNET ACCESS_NETWORK_STATE CALL_PHONE SEND_...,forceLoad setInternalPageChangeListener execut...,android.provider.Telephony.SMS_RECEIVED androi...,invoke-direct return-void const/4 return const...,...,False,False,False,False,False,False,False,False,False,False
3,9bc351f77a9833e9665c478cfbcc0e93c27daa1ebd454c...,310298,16.0,1334.0,40225.0,3.0,SEND_SMS READ_CONTACTS INTERNET CHANGE_WIFI_ST...,onMediaButtonUp setInternalPageChangeListener ...,android.provider.Telephony.SMS_RECEIVED androi...,invoke-direct return-void AG:invalid_instructi...,...,False,False,False,False,False,False,False,False,False,False
4,21c3a37c3405a5f56b77c4ec49e9e34143754f7381a0b4...,455629,11.0,139.0,20673.0,5.0,SEND_SMS READ_CONTACTS INTERNET WRITE_SMS WRIT...,equals u onBackPressed drawChild setScrollStat...,android.intent.action.BOOT_COMPLETED android.i...,sget const/16 if-lt invoke-static new-instance...,...,False,False,False,False,False,False,False,False,False,False

In [13]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

text_features = ['PERM', 'API', 'INTENT', 'OPCODE']
vectorizers = {}
processed_text_features = pd.DataFrame()

for col in text_features:
    # Use TfidfVectorizer for each text column
    vectorizer = TfidfVectorizer(max_features=5000) # Limiting features to manage dimensionality
    # Fit and transform the data
    tfidf_matrix = vectorizer.fit_transform(df[col])

    # Convert TF-IDF matrix to a DataFrame and append to processed_text_features
    tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=[f'{col}_{i}' for i in range(tfidf_matrix.shape[1])])
    processed_text_features = pd.concat([processed_text_features, tfidf_df], axis=1)

    vectorizers[col] = vectorizer
    print(f"Processed column '{col}'. Shape of TF-IDF matrix: {tfidf_matrix.shape}")

# Drop original text columns from df and concatenate with processed_text_features
df = df.drop(columns=text_features)
df = pd.concat([df, processed_text_features], axis=1)

print("\nDataFrame shape after TF-IDF vectorization:")
print(df.shape)
print("First 5 rows of DataFrame after TF-IDF vectorization (showing some new columns):")
display(df.head())

ValueError: np.nan is an invalid document, expected byte or unicode string.

In [14]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/00 IITR INTERNSHIP/00_final_dataset.csv")

In [15]:
df['apk_size'] = pd.to_numeric(df['apk_size'], errors='coerce')
df['apk_size'] = df['apk_size'].fillna(df['apk_size'].median())
print('Data type of apk_size after conversion and imputation:')
print(df['apk_size'].dtype)
print('\nDescriptive statistics of apk_size after conversion and imputation:')
display(df['apk_size'].describe())

Data type of apk_size after conversion and imputation:
float64

Descriptive statistics of apk_size after conversion and imputation:

count    5.007000e+03
mean     4.606476e+06
std      8.047840e+06
min      8.812000e+03
25%      3.105570e+05
50%      1.011092e+06
75%      4.829922e+06
max      6.274566e+07
Name: apk_size, dtype: float64

In [16]:
numerical_cols_with_na = ['permission_count', 'api_count', 'opcode_count', 'intent_count']
for col in numerical_cols_with_na:
    df[col] = df[col].fillna(df[col].median())
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print("\nMissing values in 'family' before imputation:")
print(df['family'].isnull().sum())

df['family'] = df['family'].fillna(df['family'].mode()[0])
print("Missing values in 'family' after imputation:")
print(df['family'].isnull().sum())

print("\nUnique values and counts for 'family' after imputation:")
print(df['family'].value_counts())

Missing values in permission_count after imputation: 0
Missing values in api_count after imputation: 0
Missing values in opcode_count after imputation: 0
Missing values in intent_count after imputation: 0

Missing values in 'family' before imputation:
9
Missing values in 'family' after imputation:
0

Unique values and counts for 'family' after imputation:
family
SMS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1098
Benign3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1060
Banking                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               986
Adware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                966
Riskware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              889
android.provider.Telephony.SMS_RECEIVED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.RECEIVE net.peakgames.Yuzbir.AUTO_CAMPAIGN_ACTION net.peakgames.Yuzbir.TIME_BONUS_ACTION                                                                                                                                                                                                                                                                                                                                                                                                                          1
com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_DELETED android.appwidget.action.APPWIDGET_ENABLED android.appwidget.action.APPWIDGET_DISABLED com.android.vending.INSTALL_REFERRER com.google.android.c2dm.intent.RECEIVE com.google.android.gms.measurement.UPLOAD                                                                                                                                                                                                                                                                                       1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_UPDATE com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                        1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.jamplay.jamplaymobile.android.intent.APPBOY_PUSH_RECEIVED com.jamplay.jamplaymobile.android.intent.APPBOY_NOTIFICATION_OPENED com.android.vending.INSTALL_REFERRER                                                                                                                                                                                                                                                                                                                               1
com.inmobi.share.id android.net.conn.CONNECTIVITY_CHANGE com.android.vending.billing.IN_APP_NOTIFY com.android.vending.billing.RESPONSE_CODE com.android.vending.billing.PURCHASE_STATE_CHANGED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION android.net.conn.CONNECTIVITY_CHANGE com.google.android.gms.measurement.UPLOAD android.provider.Telephony.SECRET_CODE                                                                                                                                                                                1
android.intent.action.BOOT_COMPLETED android.net.conn.CONNECTIVITY_CHANGE com.urbanairship.push.CHANNEL_UPDATED com.urbanairship.push.OPENED com.urbanairship.push.RECEIVED com.urbanairship.push.DISMISSED com.android.vending.INSTALL_REFERRER android.appwidget.action.APPWIDGET_UPDATE com.android.vending.INSTALL_REFERRER android.intent.action.PACKAGE_REPLACED com.urbanairship.push.OPENED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.amazon.device.messaging.intent.REGISTRATION com.amazon.device.messaging.intent.RECEIVE       1
Name: count, dtype: int64

In [17]:
text_cols_with_na = ['PERM', 'API', 'INTENT', 'OPCODE']
for col in text_cols_with_na:
    df[col] = df[col].fillna('')
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print('\nTotal missing values after all imputations:')
print(df.isnull().sum())

Missing values in PERM after imputation: 0
Missing values in API after imputation: 0
Missing values in INTENT after imputation: 0
Missing values in OPCODE after imputation: 0

Total missing values after all imputations:
file_name           0
family              0
apk_size            0
permission_count    0
api_count           0
opcode_count        0
intent_count        0
PERM                0
API                 0
INTENT              0
OPCODE              0
dtype: int64

In [18]:
import pandas as pd
df = pd.get_dummies(df, columns=['family'], prefix='family', drop_first=True)
print("DataFrame shape after one-hot encoding 'family' column:")
print(df.shape)
print("First 5 rows of DataFrame after encoding:")
display(df.head())

DataFrame shape after one-hot encoding 'family' column:
(5007, 22)
First 5 rows of DataFrame after encoding:

,file_name,apk_size,permission_count,api_count,opcode_count,intent_count,PERM,API,INTENT,OPCODE,...,family_Riskware,family_SMS,family_android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_DELETED android.appwidget.action.APPWIDGET_ENABLED android.appwidget.action.APPWIDGET_DISABLED com.android.vending.INSTALL_REFERRER com.google.android.c2dm.intent.RECEIVE com.google.android.gms.measurement.UPLOAD,family_android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_UPDATE com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION,family_android.intent.action.BOOT_COMPLETED android.net.conn.CONNECTIVITY_CHANGE com.urbanairship.push.CHANNEL_UPDATED com.urbanairship.push.OPENED com.urbanairship.push.RECEIVED com.urbanairship.push.DISMISSED com.android.vending.INSTALL_REFERRER android.appwidget.action.APPWIDGET_UPDATE com.android.vending.INSTALL_REFERRER android.intent.action.PACKAGE_REPLACED com.urbanairship.push.OPENED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.amazon.device.messaging.intent.REGISTRATION com.amazon.device.messaging.intent.RECEIVE,family_android.provider.Telephony.SMS_RECEIVED,family_com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.RECEIVE net.peakgames.Yuzbir.AUTO_CAMPAIGN_ACTION net.peakgames.Yuzbir.TIME_BONUS_ACTION,family_com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.jamplay.jamplaymobile.android.intent.APPBOY_PUSH_RECEIVED com.jamplay.jamplaymobile.android.intent.APPBOY_NOTIFICATION_OPENED com.android.vending.INSTALL_REFERRER,family_com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION,family_com.inmobi.share.id android.net.conn.CONNECTIVITY_CHANGE com.android.vending.billing.IN_APP_NOTIFY com.android.vending.billing.RESPONSE_CODE com.android.vending.billing.PURCHASE_STATE_CHANGED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION android.net.conn.CONNECTIVITY_CHANGE com.google.android.gms.measurement.UPLOAD android.provider.Telephony.SECRET_CODE
0,51ac87b5dc1c12f3dfe43cd2114c28a845699308a2803c...,246751.0,23.0,889.0,27530.0,8.0,INTERNET ACCESS_NETWORK_STATE CALL_PHONE SEND_...,forceLoad setInternalPageChangeListener execut...,android.provider.Telephony.SMS_RECEIVED androi...,invoke-direct return-void add-double unresolve...,...,False,False,False,False,False,False,False,False,False,False
1,1b16adaa855a73b75224d76058b72e6b39d8178a58ad08...,251248.0,16.0,1305.0,36584.0,7.0,SEND_SMS READ_CONTACTS READ_EXTERNAL_STORAGE W...,setInternalPageChangeListener setPassword getM...,android.intent.action.BOOT_COMPLETED android.i...,invoke-direct new-instance invoke-direct iput-...,...,False,False,False,False,False,False,False,False,False,False
2,3ef61e6781e76c13ab7d5519bc094db1dd2bfbf1ea8bf1...,230784.0,23.0,887.0,27394.0,8.0,INTERNET ACCESS_NETWORK_STATE CALL_PHONE SEND_...,forceLoad setInternalPageChangeListener execut...,android.provider.Telephony.SMS_RECEIVED androi...,invoke-direct return-void const/4 return const...,...,False,False,False,False,False,False,False,False,False,False
3,9bc351f77a9833e9665c478cfbcc0e93c27daa1ebd454c...,310298.0,16.0,1334.0,40225.0,3.0,SEND_SMS READ_CONTACTS INTERNET CHANGE_WIFI_ST...,onMediaButtonUp setInternalPageChangeListener ...,android.provider.Telephony.SMS_RECEIVED androi...,invoke-direct return-void AG:invalid_instructi...,...,False,False,False,False,False,False,False,False,False,False
4,21c3a37c3405a5f56b77c4ec49e9e34143754f7381a0b4...,455629.0,11.0,139.0,20673.0,5.0,SEND_SMS READ_CONTACTS INTERNET WRITE_SMS WRIT...,equals u onBackPressed drawChild setScrollStat...,android.intent.action.BOOT_COMPLETED android.i...,sget const/16 if-lt invoke-static new-instance...,...,False,False,False,False,False,False,False,False,False,False

In [19]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

text_features = ['PERM', 'API', 'INTENT', 'OPCODE']
vectorizers = {}
processed_text_features = pd.DataFrame()

for col in text_features:
    # Use TfidfVectorizer for each text column
    vectorizer = TfidfVectorizer(max_features=5000) # Limiting features to manage dimensionality
    # Fit and transform the data
    tfidf_matrix = vectorizer.fit_transform(df[col])

    # Convert TF-IDF matrix to a DataFrame and append to processed_text_features
    tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=[f'{col}_{i}' for i in range(tfidf_matrix.shape[1])])
    processed_text_features = pd.concat([processed_text_features, tfidf_df], axis=1)

    vectorizers[col] = vectorizer
    print(f"Processed column '{col}'. Shape of TF-IDF matrix: {tfidf_matrix.shape}")

# Drop original text columns from df and concatenate with processed_text_features
df = df.drop(columns=text_features)
df = pd.concat([df, processed_text_features], axis=1)

print("\nDataFrame shape after TF-IDF vectorization:")
print(df.shape)
print("First 5 rows of DataFrame after TF-IDF vectorization (showing some new columns):")
display(df.head())

Processed column 'PERM'. Shape of TF-IDF matrix: (5007, 563)
Processed column 'API'. Shape of TF-IDF matrix: (5007, 5000)
Processed column 'INTENT'. Shape of TF-IDF matrix: (5007, 2749)
Processed column 'OPCODE'. Shape of TF-IDF matrix: (5007, 93)

DataFrame shape after TF-IDF vectorization:
(5007, 8423)
First 5 rows of DataFrame after TF-IDF vectorization (showing some new columns):

,file_name,apk_size,permission_count,api_count,opcode_count,intent_count,family_Banking,family_Benign3,family_Riskware,family_SMS,...,OPCODE_83,OPCODE_84,OPCODE_85,OPCODE_86,OPCODE_87,OPCODE_88,OPCODE_89,OPCODE_90,OPCODE_91,OPCODE_92
0,51ac87b5dc1c12f3dfe43cd2114c28a845699308a2803c...,246751.0,23.0,889.0,27530.0,8.0,True,False,False,False,...,0.008242,0.010798,0.026701,0.000000,0.009522,0.002286,0.370407,0.069245,0.000000,0.002489
1,1b16adaa855a73b75224d76058b72e6b39d8178a58ad08...,251248.0,16.0,1305.0,36584.0,7.0,True,False,False,False,...,0.004410,0.003531,0.010984,0.000815,0.000000,0.000000,0.368494,0.112785,0.042452,0.001221
2,3ef61e6781e76c13ab7d5519bc094db1dd2bfbf1ea8bf1...,230784.0,23.0,887.0,27394.0,8.0,True,False,False,False,...,0.008944,0.011636,0.026560,0.000000,0.000000,0.000000,0.370407,0.068880,0.000000,0.001238
3,9bc351f77a9833e9665c478cfbcc0e93c27daa1ebd454c...,310298.0,16.0,1334.0,40225.0,3.0,True,False,False,False,...,0.002316,0.011125,0.016860,0.004279,0.019620,0.000000,0.339809,0.068647,0.000929,0.001282
4,21c3a37c3405a5f56b77c4ec49e9e34143754f7381a0b4...,455629.0,11.0,139.0,20673.0,5.0,True,False,False,False,...,0.019426,0.006666,0.017546,0.000000,0.000000,0.000000,0.396315,0.061700,0.000000,0.000000

In [9]:
df = pd.read_csv("/content/drive/MyDrive/00 IITR INTERNSHIP/00_final_dataset.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/00 IITR INTERNSHIP/00_final_dataset.csv'

In [10]:
print('Missing values in each column:')
print(df.isnull().sum())

Missing values in each column:
file_name              0
family                 0
apk_size               0
permission_count       0
api_count              0
opcode_count           0
intent_count           0
PERM                  33
API                   46
INTENT              1140
OPCODE                46
dtype: int64

In [14]:
df['apk_size'] = pd.to_numeric(df['apk_size'], errors='coerce')
df['apk_size'] = df['apk_size'].fillna(df['apk_size'].median())
print('Data type of apk_size after conversion and imputation:')
print(df['apk_size'].dtype)
print('\nDescriptive statistics of apk_size after conversion and imputation:')
display(df['apk_size'].describe())

Data type of apk_size after conversion and imputation:
float64

Descriptive statistics of apk_size after conversion and imputation:

count    5.007000e+03
mean     4.606476e+06
std      8.047840e+06
min      8.812000e+03
25%      3.105570e+05
50%      1.011092e+06
75%      4.829922e+06
max      6.274566e+07
Name: apk_size, dtype: float64

In [15]:
numerical_cols_with_na = ['permission_count', 'api_count', 'opcode_count', 'intent_count']
for col in numerical_cols_with_na:
    df[col] = df[col].fillna(df[col].median())
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print("\nMissing values in 'family' before imputation:")
print(df['family'].isnull().sum())

df['family'] = df['family'].fillna(df['family'].mode()[0])
print("Missing values in 'family' after imputation:")
print(df['family'].isnull().sum())

print("\nUnique values and counts for 'family' after imputation:")
print(df['family'].value_counts())

Missing values in permission_count after imputation: 0
Missing values in api_count after imputation: 0
Missing values in opcode_count after imputation: 0
Missing values in intent_count after imputation: 0

Missing values in 'family' before imputation:
0
Missing values in 'family' after imputation:
0

Unique values and counts for 'family' after imputation:
family
SMS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1098
Benign3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1060
Banking                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               986
Adware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                966
Riskware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              889
android.provider.Telephony.SMS_RECEIVED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.RECEIVE net.peakgames.Yuzbir.AUTO_CAMPAIGN_ACTION net.peakgames.Yuzbir.TIME_BONUS_ACTION                                                                                                                                                                                                                                                                                                                                                                                                                          1
com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_DELETED android.appwidget.action.APPWIDGET_ENABLED android.appwidget.action.APPWIDGET_DISABLED com.android.vending.INSTALL_REFERRER com.google.android.c2dm.intent.RECEIVE com.google.android.gms.measurement.UPLOAD                                                                                                                                                                                                                                                                                       1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_UPDATE com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                        1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.jamplay.jamplaymobile.android.intent.APPBOY_PUSH_RECEIVED com.jamplay.jamplaymobile.android.intent.APPBOY_NOTIFICATION_OPENED com.android.vending.INSTALL_REFERRER                                                                                                                                                                                                                                                                                                                               1
com.inmobi.share.id android.net.conn.CONNECTIVITY_CHANGE com.android.vending.billing.IN_APP_NOTIFY com.android.vending.billing.RESPONSE_CODE com.android.vending.billing.PURCHASE_STATE_CHANGED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION android.net.conn.CONNECTIVITY_CHANGE com.google.android.gms.measurement.UPLOAD android.provider.Telephony.SECRET_CODE                                                                                                                                                                                1
android.intent.action.BOOT_COMPLETED android.net.conn.CONNECTIVITY_CHANGE com.urbanairship.push.CHANNEL_UPDATED com.urbanairship.push.OPENED com.urbanairship.push.RECEIVED com.urbanairship.push.DISMISSED com.android.vending.INSTALL_REFERRER android.appwidget.action.APPWIDGET_UPDATE com.android.vending.INSTALL_REFERRER android.intent.action.PACKAGE_REPLACED com.urbanairship.push.OPENED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.amazon.device.messaging.intent.REGISTRATION com.amazon.device.messaging.intent.RECEIVE       1
Name: count, dtype: int64

In [21]:
text_cols_with_na = ['PERM', 'API', 'INTENT', 'OPCODE']
for col in text_cols_with_na:
    df[col] = df[col].fillna('')
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print('\nTotal missing values after all imputations:')
print(df.isnull().sum())

Missing values in PERM after imputation: 0
Missing values in API after imputation: 0
Missing values in INTENT after imputation: 0
Missing values in OPCODE after imputation: 0

Total missing values after all imputations:
file_name           0
family              0
apk_size            0
permission_count    0
api_count           0
opcode_count        0
intent_count        0
PERM                0
API                 0
INTENT              0
OPCODE              0
dtype: int64

In [22]:
text_cols_with_na = ['PERM', 'API', 'INTENT', 'OPCODE']
for col in text_cols_with_na:
    df[col] = df[col].fillna('')
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print('\nTotal missing values after all imputations:')
print(df.isnull().sum())

Missing values in PERM after imputation: 0
Missing values in API after imputation: 0
Missing values in INTENT after imputation: 0
Missing values in OPCODE after imputation: 0

Total missing values after all imputations:
file_name           0
family              0
apk_size            0
permission_count    0
api_count           0
opcode_count        0
intent_count        0
PERM                0
API                 0
INTENT              0
OPCODE              0
dtype: int64

In [23]:
text_cols_with_na = ['PERM', 'API', 'INTENT', 'OPCODE']
for col in text_cols_with_na:
    df[col] = df[col].fillna('')
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print('\nTotal missing values after all imputations:')
print(df.isnull().sum())

Missing values in PERM after imputation: 0
Missing values in API after imputation: 0
Missing values in INTENT after imputation: 0
Missing values in OPCODE after imputation: 0

Total missing values after all imputations:
file_name           0
family              0
apk_size            0
permission_count    0
api_count           0
opcode_count        0
intent_count        0
PERM                0
API                 0
INTENT              0
OPCODE              0
dtype: int64

In [5]:
import pandas as pd
df = pd.get_dummies(df, columns=['family'], prefix='family', drop_first=True)
print("DataFrame shape after one-hot encoding 'family' column:")
print(df.shape)
print("First 5 rows of DataFrame after encoding:")
display(df.head())

NameError: name 'df' is not defined

In [6]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

text_features = ['PERM', 'API', 'INTENT', 'OPCODE']
vectorizers = {}
processed_text_features = pd.DataFrame()

for col in text_features:
    # Use TfidfVectorizer for each text column
    vectorizer = TfidfVectorizer(max_features=5000) # Limiting features to manage dimensionality
    # Fit and transform the data
    tfidf_matrix = vectorizer.fit_transform(df[col])

    # Convert TF-IDF matrix to a DataFrame and append to processed_text_features
    tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=[f'{col}_{i}' for i in range(tfidf_matrix.shape[1])])
    processed_text_features = pd.concat([processed_text_features, tfidf_df], axis=1)

    vectorizers[col] = vectorizer
    print(f"Processed column '{col}'. Shape of TF-IDF matrix: {tfidf_matrix.shape}")

# Drop original text columns from df and concatenate with processed_text_features
df = df.drop(columns=text_features)
df = pd.concat([df, processed_text_features], axis=1)

print("\nDataFrame shape after TF-IDF vectorization:")
print(df.shape)
print("First 5 rows of DataFrame after TF-IDF vectorization (showing some new columns):")
display(df.head())

NameError: name 'df' is not defined

In [7]:
import pandas as pd
df = pd.get_dummies(df, columns=['family'], prefix='family', drop_first=True)
print("DataFrame shape after one-hot encoding 'family' column:")
print(df.shape)
print("First 5 rows of DataFrame after encoding:")
display(df.head())

NameError: name 'df' is not defined

In [8]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

text_features = ['PERM', 'API', 'INTENT', 'OPCODE']
vectorizers = {}
processed_text_features = pd.DataFrame()

for col in text_features:
    # Use TfidfVectorizer for each text column
    vectorizer = TfidfVectorizer(max_features=5000) # Limiting features to manage dimensionality
    # Fit and transform the data
    tfidf_matrix = vectorizer.fit_transform(df[col])

    # Convert TF-IDF matrix to a DataFrame and append to processed_text_features
    tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=[f'{col}_{i}' for i in range(tfidf_matrix.shape[1])])
    processed_text_features = pd.concat([processed_text_features, tfidf_df], axis=1)

    vectorizers[col] = vectorizer
    print(f"Processed column '{col}'. Shape of TF-IDF matrix: {tfidf_matrix.shape}")

# Drop original text columns from df and concatenate with processed_text_features
df = df.drop(columns=text_features)
df = pd.concat([df, processed_text_features], axis=1)

print("\nDataFrame shape after TF-IDF vectorization:")
print(df.shape)
print("First 5 rows of DataFrame after TF-IDF vectorization (showing some new columns):")
display(df.head())

NameError: name 'df' is not defined

In [24]:
text_cols_with_na = ['PERM', 'API', 'INTENT', 'OPCODE']
for col in text_cols_with_na:
    df[col] = df[col].fillna('')
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print('\nTotal missing values after all imputations:')
print(df.isnull().sum())

Missing values in PERM after imputation: 0
Missing values in API after imputation: 0
Missing values in INTENT after imputation: 0
Missing values in OPCODE after imputation: 0

Total missing values after all imputations:
file_name           0
family              0
apk_size            0
permission_count    0
api_count           0
opcode_count        0
intent_count        0
PERM                0
API                 0
INTENT              0
OPCODE              0
dtype: int64

In [25]:
text_cols_with_na = ['PERM', 'API', 'INTENT', 'OPCODE']
for col in text_cols_with_na:
    df[col] = df[col].fillna('')
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print('\nTotal missing values after all imputations:')
print(df.isnull().sum())

Missing values in PERM after imputation: 0
Missing values in API after imputation: 0
Missing values in INTENT after imputation: 0
Missing values in OPCODE after imputation: 0

Total missing values after all imputations:
file_name           0
family              0
apk_size            0
permission_count    0
api_count           0
opcode_count        0
intent_count        0
PERM                0
API                 0
INTENT              0
OPCODE              0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5007 entries, 0 to 5006
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   file_name         5007 non-null   object
 1   family            4998 non-null   object
 2   apk_size          5000 non-null   object
 3   permission_count  4990 non-null   float64
 4   api_count         4990 non-null   float64
 5   opcode_count      4990 non-null   float64
 6   intent_count      4990 non-null   float64
 7   PERM              4974 non-null   object
 8   API               4961 non-null   object
 9   INTENT            3867 non-null   object
 10  OPCODE            4961 non-null   object
dtypes: float64(4), object(7)
memory usage: 430.4+ KB

In [16]:
df['apk_size'] = pd.to_numeric(df['apk_size'], errors='coerce')
df['apk_size'] = df['apk_size'].fillna(df['apk_size'].median())
print('Data type of apk_size after conversion and imputation:')
print(df['apk_size'].dtype)
print('\nDescriptive statistics of apk_size after conversion and imputation:')
display(df['apk_size'].describe())

Data type of apk_size after conversion and imputation:
float64

Descriptive statistics of apk_size after conversion and imputation:

count    5.007000e+03
mean     4.606476e+06
std      8.047840e+06
min      8.812000e+03
25%      3.105570e+05
50%      1.011092e+06
75%      4.829922e+06
max      6.274566e+07
Name: apk_size, dtype: float64

In [17]:
numerical_cols_with_na = ['permission_count', 'api_count', 'opcode_count', 'intent_count']
for col in numerical_cols_with_na:
    df[col] = df[col].fillna(df[col].median())
    print(f"Missing values in {col} after imputation: {df[col].isnull().sum()}")

print("\nMissing values in 'family' before imputation:")
print(df['family'].isnull().sum())

df['family'] = df['family'].fillna(df['family'].mode()[0])
print("Missing values in 'family' after imputation:")
print(df['family'].isnull().sum())

print("\nUnique values and counts for 'family' after imputation:")
print(df['family'].value_counts())

Missing values in permission_count after imputation: 0
Missing values in api_count after imputation: 0
Missing values in opcode_count after imputation: 0
Missing values in intent_count after imputation: 0

Missing values in 'family' before imputation:
0
Missing values in 'family' after imputation:
0

Unique values and counts for 'family' after imputation:
family
SMS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1098
Benign3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1060
Banking                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               986
Adware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                966
Riskware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              889
android.provider.Telephony.SMS_RECEIVED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.RECEIVE net.peakgames.Yuzbir.AUTO_CAMPAIGN_ACTION net.peakgames.Yuzbir.TIME_BONUS_ACTION                                                                                                                                                                                                                                                                                                                                                                                                                          1
com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_DELETED android.appwidget.action.APPWIDGET_ENABLED android.appwidget.action.APPWIDGET_DISABLED com.android.vending.INSTALL_REFERRER com.google.android.c2dm.intent.RECEIVE com.google.android.gms.measurement.UPLOAD                                                                                                                                                                                                                                                                                       1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_UPDATE com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                        1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.jamplay.jamplaymobile.android.intent.APPBOY_PUSH_RECEIVED com.jamplay.jamplaymobile.android.intent.APPBOY_NOTIFICATION_OPENED com.android.vending.INSTALL_REFERRER                                                                                                                                                                                                                                                                                                                               1
com.inmobi.share.id android.net.conn.CONNECTIVITY_CHANGE com.android.vending.billing.IN_APP_NOTIFY com.android.vending.billing.RESPONSE_CODE com.android.vending.billing.PURCHASE_STATE_CHANGED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION android.net.conn.CONNECTIVITY_CHANGE com.google.android.gms.measurement.UPLOAD android.provider.Telephony.SECRET_CODE                                                                                                                                                                                1
android.intent.action.BOOT_COMPLETED android.net.conn.CONNECTIVITY_CHANGE com.urbanairship.push.CHANNEL_UPDATED com.urbanairship.push.OPENED com.urbanairship.push.RECEIVED com.urbanairship.push.DISMISSED com.android.vending.INSTALL_REFERRER android.appwidget.action.APPWIDGET_UPDATE com.android.vending.INSTALL_REFERRER android.intent.action.PACKAGE_REPLACED com.urbanairship.push.OPENED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.amazon.device.messaging.intent.REGISTRATION com.amazon.device.messaging.intent.RECEIVE       1
Name: count, dtype: int64

In [18]:
print('Missing values in each column:')
print(df.isnull().sum())

Missing values in each column:
file_name              0
family                 0
apk_size               0
permission_count       0
api_count              0
opcode_count           0
intent_count           0
PERM                  33
API                   46
INTENT              1140
OPCODE                46
dtype: int64

In [5]:
display(df.describe(include='all'))

,file_name,family,apk_size,permission_count,api_count,opcode_count,intent_count,PERM,API,INTENT,OPCODE
count,5007,4998,5000,4990.000000,4990.000000,4.990000e+03,4990.000000,4974,4961,3867,4961
unique,5007,13,4567,NaN,NaN,NaN,NaN,2008,2763,1254,2100
top,4ce2c46fd9d88b2a2552eda6f4afc4c7e19043909fd92a...,SMS,19023,NaN,NaN,NaN,NaN,WRITE_INTERNAL_STORAGE CHANGE_CONFIGURATION DI...,a b attachBaseContext <init>,android.net.conn.CONNECTIVITY_CHANGE android.i...,invoke-direct return-void invoke-super const-s...
freq,1,1089,23,NaN,NaN,NaN,NaN,201,428,200,193
mean,NaN,NaN,NaN,15.331463,2222.951904,1.573493e+05,7.869339,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,12.554693,3874.529221,2.762950e+05,11.923579,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,7.000000,79.000000,3.576000e+03,1.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,12.000000,371.000000,2.743300e+04,4.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,19.000000,2139.000000,1.495888e+05,9.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,169.000000,33177.000000,4.033173e+06,198.000000,NaN,NaN,NaN,NaN

From the information above, we can see the data types and get a basic understanding of numerical and categorical columns.

Next, let's explore unique values in categorical columns and check for any missing values.

In [6]:
for col in df.select_dtypes(include='object').columns:
    print(f"Column '{col}': {df[col].nunique()} unique values")
    if df[col].nunique() < 50: # Display unique values if not too many
        print(df[col].value_counts())
    print("\n")

print("Missing values:")
print(df.isnull().sum())

Column 'file_name': 5007 unique values


Column 'family': 13 unique values
family
SMS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1089
Benign3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1060
Banking                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               986
Adware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                966
Riskware                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              889
android.provider.Telephony.SMS_RECEIVED                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.RECEIVE net.peakgames.Yuzbir.AUTO_CAMPAIGN_ACTION net.peakgames.Yuzbir.TIME_BONUS_ACTION                                                                                                                                                                                                                                                                                                                                                                                                                          1
com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_DELETED android.appwidget.action.APPWIDGET_ENABLED android.appwidget.action.APPWIDGET_DISABLED com.android.vending.INSTALL_REFERRER com.google.android.c2dm.intent.RECEIVE com.google.android.gms.measurement.UPLOAD                                                                                                                                                                                                                                                                                       1
android.appwidget.action.APPWIDGET_UPDATE android.appwidget.action.APPWIDGET_UPDATE com.google.android.gms.measurement.UPLOAD com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION                                                                                                                                                                                                                                                                                                                                                                        1
com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.jamplay.jamplaymobile.android.intent.APPBOY_PUSH_RECEIVED com.jamplay.jamplaymobile.android.intent.APPBOY_NOTIFICATION_OPENED com.android.vending.INSTALL_REFERRER                                                                                                                                                                                                                                                                                                                               1
com.inmobi.share.id android.net.conn.CONNECTIVITY_CHANGE com.android.vending.billing.IN_APP_NOTIFY com.android.vending.billing.RESPONSE_CODE com.android.vending.billing.PURCHASE_STATE_CHANGED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION android.net.conn.CONNECTIVITY_CHANGE com.google.android.gms.measurement.UPLOAD android.provider.Telephony.SECRET_CODE                                                                                                                                                                                1
android.intent.action.BOOT_COMPLETED android.net.conn.CONNECTIVITY_CHANGE com.urbanairship.push.CHANNEL_UPDATED com.urbanairship.push.OPENED com.urbanairship.push.RECEIVED com.urbanairship.push.DISMISSED com.android.vending.INSTALL_REFERRER android.appwidget.action.APPWIDGET_UPDATE com.android.vending.INSTALL_REFERRER android.intent.action.PACKAGE_REPLACED com.urbanairship.push.OPENED com.google.android.c2dm.intent.RECEIVE com.google.android.c2dm.intent.REGISTRATION com.amazon.device.messaging.intent.REGISTRATION com.amazon.device.messaging.intent.RECEIVE       1
Name: count, dtype: int64


Column 'apk_size': 4567 unique values


Column 'PERM': 2008 unique values


Column 'API': 2763 unique values


Column 'INTENT': 1254 unique values


Column 'OPCODE': 2100 unique values


Missing values:
file_name              0
family                 9
apk_size               7
permission_count      17
api_count             17
opcode_count          17
intent_count          17
PERM                  33
API                   46
INTENT              1140
OPCODE                46
dtype: int64